[tox]
minversion = 4.0
envlist = py38, py39, py310, py311, py312, py313, geo, ruff, mypy, package
isolated_build = true

[gh-actions]
python =
    3.8: py38
    3.9: py39
    3.10: py310
    3.11: py311
    3.12: py312
    3.13: py313

[testenv]
package = wheel
extras = dev
setenv =
    COVERAGE_FILE = {envdir}/.coverage
commands = python -m pytest --basetemp={envtmpdir} --cov-report=html:{envdir}/htmlcov --cov-report=xml:{envdir}/coverage.xml

[testenv:geo]
extras = dev, geo
commands = python -m pytest --basetemp={envtmpdir} --cov-report=html:{envdir}/htmlcov --cov-report=xml:{envdir}/coverage.xml --cov-fail-under=85

[testenv:ruff]
package = skip
deps = ruff
commands =
    ruff check src tests
    ruff format --check src tests

[testenv:mypy]
extras = dev
commands = mypy src

[testenv:package]
package = skip
deps =
    build
    twine
commands =
    python -m build
    python -m twine check --strict {toxinidir}/dist/landfall-0.5.0.tar.gz {toxinidir}/dist/landfall-0.5.0-py3-none-any.whl
